language: python

python:
  - "3.6"

install:
  - make venv

branches:
  only:
  - master
  - develop

script:
  - make test

after_success:
  - make codecov

notifications:
  email:
    recipients:
      - nikolay.lysenko.1992@gmail.com
    on_success: never
    on_failure: always
