name: build

on:
  push:
    branches:
      - master
      - develop

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.9]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements/test.txt
    - name: Lint with Flake8
      run: flake8 .
    - name: Test with Pytest
      run: pytest --cov=readingbricks --cov-config .coveragerc
    - name: Create and upload Codecov report
      uses: codecov/codecov-action@v1
      with:
        fail_ci_if_error: true

